# -*- coding: utf-8 -*-
"""Marking words 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qwOgaO8UmpgebGi4oBaAD7Z6gNG9AFiT
"""

import random
from google.colab import files
files.upload()
def read_words():
    with open('words.txt', 'r') as f:
        words = f.read().splitlines()
    return words

def start_game():
    words = read_words()
    correct_answers = 0
    incorrect_answers = 0

    while True:
        word = random.choice(words)
        print(f"Word: {word}")
        answer = input("Is it a marking word? (y/n): ")

        if answer.lower() == 'y':
            if word in marking_words:
                print("Correct!")
                correct_answers += 1
            else:
                print("Incorrect.")
                incorrect_answers += 1
        elif answer.lower() == 'n':
            if word not in marking_words:
                print("Correct!")
                correct_answers += 1
            else:
                print("Incorrect.")
                incorrect_answers += 1
        else:
            print("Invalid input. Please enter y or n.")

        play_again = input("Play again? (y/n): ")
        if play_again.lower() != 'y':
            break

    print(f"Final score: {correct_answers}/{correct_answers+incorrect_answers}")

if __name__ == "__main__":
    marking_words = ["the", "a", "an", "in", "on", "at", "to", "from", "by", "with"]
    start_game()



The words list for marking are words.txt copy below list and create a text file use to run code.
    
"the
a
an
in
on
at
to
from
by
with
for
as
of
than
like
because
since
when
until
if
after
before
during
while
although
though
even though
despite
unless
except
if
whether
not
only
but
nor
either
or
both
neither
so
too
as
much
as
most
more
less
than
enough
very
quite
rather
pretty
fairly
extremely
nearly
almost
hardly
scarcely
just
barely
still
yet
already
moreover
besides
furthermore
also
as well
too
too
again
once
twice
three times
etc.
first
second
third
fourth
fifth
sixth
seventh
eighth
ninth
tenth
last
next
previous
former
latter
past
present
future
early
late
early
late
soon
later
on time
late
late
today
tomorrow
yesterday
last week
next week
this week
last year
next year
this year
January
February
March
April
May
June
July
August
September
October
November
December
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
spring
summer
fall
winter
morning
noon
afternoon
evening
night
day
night
today
tomorrow
yesterday
one
two
three
four
five
six
seven
eight
nine
ten
eleven
twelve
thirteen
fourteen
fifteen
sixteen
seventeen
eighteen
nineteen
twenty
thirty
forty
fifty
sixty
seventy
eighty
ninety
hundred
thousand
million
billion
trillion
zero
positive
negative
integer
decimal
fraction
fraction
rational
irrational
real
imaginary
complex
prime
composite
even
odd
multiple
factor
gcd
lcm
exponent
power
base
root
logarithm
equation
inequality
function
graph
slope
y-intercept
x-intercept
domain
range
limit
derivative
integral
differentiable
integrable
continuous
discontinuous
asymptote
tangent
secant
normal
radius
diameter
circumference
area
volume
pi"
